// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuranApi;

#nullable disable

namespace QuranApi.Migrations
{
    [DbContext(typeof(QuranDbContext))]
    [Migration("20240831061838_totalRukuIDColumnAdded")]
    partial class totalRukuIDColumnAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuranApi.Models.Ayah", b =>
                {
                    b.Property<int?>("AyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AyaID"));

                    b.Property<string>("ArabicText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AyaNo")
                        .HasColumnType("int");

                    b.Property<string>("DrMohsinKhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatehMuhammadJalandhrield")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MehmoodulHassan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuftiTaqiUsmani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PRakuID")
                        .HasColumnType("int");

                    b.Property<int?>("ParaID")
                        .HasColumnType("int");

                    b.Property<int?>("RakuID")
                        .HasColumnType("int");

                    b.Property<int?>("SuraID")
                        .HasColumnType("int");

                    b.Property<int>("pAyatID")
                        .HasColumnType("int");

                    b.Property<int>("totalRukuCount")
                        .HasColumnType("int");

                    b.HasKey("AyaID");

                    b.ToTable("Ayah");
                });

            modelBuilder.Entity("QuranApi.Models.Para", b =>
                {
                    b.Property<int>("ParaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParaID"));

                    b.Property<string>("ArabicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAyas")
                        .HasColumnType("int");

                    b.HasKey("ParaID");

                    b.ToTable("Para");
                });

            modelBuilder.Entity("QuranApi.Models.Surah", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishNameTranslation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfAyahs")
                        .HasColumnType("int");

                    b.Property<string>("RevelationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Number");

                    b.ToTable("Surah");
                });
#pragma warning restore 612, 618
        }
    }
}
