// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuranApi;

#nullable disable

namespace QuranApi.Migrations
{
    [DbContext(typeof(QuranDbContext))]
    [Migration("20240829102321_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuranApi.Models.Ayah", b =>
                {
                    b.Property<int?>("AyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AyaID"));

                    b.Property<string>("ArabicText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AyaNo")
                        .HasColumnType("int");

                    b.Property<string>("DrMohsinKhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatehMuhammadJalandhrield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MehmoodulHassan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuftiTaqiUsmani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PRakuID")
                        .HasColumnType("int");

                    b.Property<int?>("ParaID")
                        .HasColumnType("int");

                    b.Property<int?>("RakuID")
                        .HasColumnType("int");

                    b.Property<int?>("SuraID")
                        .HasColumnType("int");

                    b.HasKey("AyaID");

                    b.ToTable("Ayah");
                });
#pragma warning restore 612, 618
        }
    }
}
